project_id = "kfhhfrsqdvdagmtqxcgu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://kfhhfrsqdvdagmtqxcgu.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.analyze-file]
verify_jwt = false

[functions.analyze-project]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[functions.jira-sync]
verify_jwt = false

[functions.jira-ai-insights]
verify_jwt = false

[functions.jira-webhook]
verify_jwt = false