// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfhhfrsqdvdagmtqxcgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmaGhmcnNxZHZkYWdtdHF4Y2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDk4NjMsImV4cCI6MjA3MTcyNTg2M30.v-obcZOvFWTiFcDnv_As_cJhnNOUPmCprN-WWZJP5Qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});